name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog git make gnat zlib1g-dev && git clone https://github.com/ghdl/ghdl && cd ghdl && ./configure --prefix=/usr/local && make && sudo make install

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cocotb 1.8.x
        shell: bash
        run: |
          pip install cocotb~=1.8.0
          cocotb-config --libpython
          cocotb-config --python-bin

      - name: Run tests
        run: |
          cd src
          ghdl --help
          ghdl -a -fsynopsys project.vhdl
          ghdl --synth -fsynopsys --out=verilog tt_um_RK444_Simple_Start > project.v
          cd ../test
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.2
        with:
          paths: "test/results.xml"
        if: always()

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/tb.vcd
            test/result.xml
